version: "1"

session:
  save_root: recordings
  record_topic: leader_left/record

nodes:
  - type: AgentNode
    name: leader_left
    agent_class: karma.agents.teleoperation.gello_leader_agent:GelloLeaderAgent
    agent_kwargs:
      port: /dev/ttyACM0
      robot_name: left
      include_gripper: true
      joint_signs: [-1, -1, -1, -1, -1, -1]
    arm_key: left
    loop_mode: flat_out

  - type: AgentNode
    name: leader_right
    agent_class: karma.agents.teleoperation.gello_leader_agent:GelloLeaderAgent
    agent_kwargs:
      port: /dev/ttyACM1
      robot_name: right
      include_gripper: true
      joint_signs: [-1, -1, -1, -1, -1, -1]
    arm_key: right
    loop_mode: flat_out

  - type: XdofSimNode
    name: sim
    scene: hybrid
    task: bottles
    camera_fps: 30.0
    viser_port: 8765
    vr_port: 8012
    cmd_topics:
      left: leader_left/joint_pos
      right: leader_right/joint_pos
